package infrastructure_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type CreateInfrastructureAccountCreated
const CreateInfrastructureAccountCreatedCode int = 201

/*CreateInfrastructureAccountCreated Infrastructure account was scheduled for creation.

swagger:response createInfrastructureAccountCreated
*/
type CreateInfrastructureAccountCreated struct {

	/*
	  In: Body
	*/
	Payload *models.InfrastructureAccount `json:"body,omitempty"`
}

// NewCreateInfrastructureAccountCreated creates CreateInfrastructureAccountCreated with default headers values
func NewCreateInfrastructureAccountCreated() *CreateInfrastructureAccountCreated {
	return &CreateInfrastructureAccountCreated{}
}

// WithPayload adds the payload to the create infrastructure account created response
func (o *CreateInfrastructureAccountCreated) WithPayload(payload *models.InfrastructureAccount) *CreateInfrastructureAccountCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create infrastructure account created response
func (o *CreateInfrastructureAccountCreated) SetPayload(payload *models.InfrastructureAccount) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateInfrastructureAccountCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type CreateInfrastructureAccountBadRequest
const CreateInfrastructureAccountBadRequestCode int = 400

/*CreateInfrastructureAccountBadRequest Invalid parameters

swagger:response createInfrastructureAccountBadRequest
*/
type CreateInfrastructureAccountBadRequest struct {
}

// NewCreateInfrastructureAccountBadRequest creates CreateInfrastructureAccountBadRequest with default headers values
func NewCreateInfrastructureAccountBadRequest() *CreateInfrastructureAccountBadRequest {
	return &CreateInfrastructureAccountBadRequest{}
}

// WriteResponse to the client
func (o *CreateInfrastructureAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// HTTP code for type CreateInfrastructureAccountUnauthorized
const CreateInfrastructureAccountUnauthorizedCode int = 401

/*CreateInfrastructureAccountUnauthorized Unauthorized

swagger:response createInfrastructureAccountUnauthorized
*/
type CreateInfrastructureAccountUnauthorized struct {
}

// NewCreateInfrastructureAccountUnauthorized creates CreateInfrastructureAccountUnauthorized with default headers values
func NewCreateInfrastructureAccountUnauthorized() *CreateInfrastructureAccountUnauthorized {
	return &CreateInfrastructureAccountUnauthorized{}
}

// WriteResponse to the client
func (o *CreateInfrastructureAccountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type CreateInfrastructureAccountForbidden
const CreateInfrastructureAccountForbiddenCode int = 403

/*CreateInfrastructureAccountForbidden Forbidden

swagger:response createInfrastructureAccountForbidden
*/
type CreateInfrastructureAccountForbidden struct {
}

// NewCreateInfrastructureAccountForbidden creates CreateInfrastructureAccountForbidden with default headers values
func NewCreateInfrastructureAccountForbidden() *CreateInfrastructureAccountForbidden {
	return &CreateInfrastructureAccountForbidden{}
}

// WriteResponse to the client
func (o *CreateInfrastructureAccountForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// HTTP code for type CreateInfrastructureAccountConflict
const CreateInfrastructureAccountConflictCode int = 409

/*CreateInfrastructureAccountConflict Conflict, already existing.

swagger:response createInfrastructureAccountConflict
*/
type CreateInfrastructureAccountConflict struct {
}

// NewCreateInfrastructureAccountConflict creates CreateInfrastructureAccountConflict with default headers values
func NewCreateInfrastructureAccountConflict() *CreateInfrastructureAccountConflict {
	return &CreateInfrastructureAccountConflict{}
}

// WriteResponse to the client
func (o *CreateInfrastructureAccountConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
}

// HTTP code for type CreateInfrastructureAccountInternalServerError
const CreateInfrastructureAccountInternalServerErrorCode int = 500

/*CreateInfrastructureAccountInternalServerError Unexpected error

swagger:response createInfrastructureAccountInternalServerError
*/
type CreateInfrastructureAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateInfrastructureAccountInternalServerError creates CreateInfrastructureAccountInternalServerError with default headers values
func NewCreateInfrastructureAccountInternalServerError() *CreateInfrastructureAccountInternalServerError {
	return &CreateInfrastructureAccountInternalServerError{}
}

// WithPayload adds the payload to the create infrastructure account internal server error response
func (o *CreateInfrastructureAccountInternalServerError) WithPayload(payload *models.Error) *CreateInfrastructureAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create infrastructure account internal server error response
func (o *CreateInfrastructureAccountInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateInfrastructureAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
