package infrastructure_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type GetInfrastructureAccountOK
const GetInfrastructureAccountOKCode int = 200

/*GetInfrastructureAccountOK Infrastructure account information.

swagger:response getInfrastructureAccountOK
*/
type GetInfrastructureAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.InfrastructureAccount `json:"body,omitempty"`
}

// NewGetInfrastructureAccountOK creates GetInfrastructureAccountOK with default headers values
func NewGetInfrastructureAccountOK() *GetInfrastructureAccountOK {
	return &GetInfrastructureAccountOK{}
}

// WithPayload adds the payload to the get infrastructure account o k response
func (o *GetInfrastructureAccountOK) WithPayload(payload *models.InfrastructureAccount) *GetInfrastructureAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get infrastructure account o k response
func (o *GetInfrastructureAccountOK) SetPayload(payload *models.InfrastructureAccount) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInfrastructureAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type GetInfrastructureAccountUnauthorized
const GetInfrastructureAccountUnauthorizedCode int = 401

/*GetInfrastructureAccountUnauthorized Unauthorized

swagger:response getInfrastructureAccountUnauthorized
*/
type GetInfrastructureAccountUnauthorized struct {
}

// NewGetInfrastructureAccountUnauthorized creates GetInfrastructureAccountUnauthorized with default headers values
func NewGetInfrastructureAccountUnauthorized() *GetInfrastructureAccountUnauthorized {
	return &GetInfrastructureAccountUnauthorized{}
}

// WriteResponse to the client
func (o *GetInfrastructureAccountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type GetInfrastructureAccountForbidden
const GetInfrastructureAccountForbiddenCode int = 403

/*GetInfrastructureAccountForbidden Forbidden

swagger:response getInfrastructureAccountForbidden
*/
type GetInfrastructureAccountForbidden struct {
}

// NewGetInfrastructureAccountForbidden creates GetInfrastructureAccountForbidden with default headers values
func NewGetInfrastructureAccountForbidden() *GetInfrastructureAccountForbidden {
	return &GetInfrastructureAccountForbidden{}
}

// WriteResponse to the client
func (o *GetInfrastructureAccountForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// HTTP code for type GetInfrastructureAccountNotFound
const GetInfrastructureAccountNotFoundCode int = 404

/*GetInfrastructureAccountNotFound InfrastructureAccount not found

swagger:response getInfrastructureAccountNotFound
*/
type GetInfrastructureAccountNotFound struct {
}

// NewGetInfrastructureAccountNotFound creates GetInfrastructureAccountNotFound with default headers values
func NewGetInfrastructureAccountNotFound() *GetInfrastructureAccountNotFound {
	return &GetInfrastructureAccountNotFound{}
}

// WriteResponse to the client
func (o *GetInfrastructureAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// HTTP code for type GetInfrastructureAccountInternalServerError
const GetInfrastructureAccountInternalServerErrorCode int = 500

/*GetInfrastructureAccountInternalServerError Unexpected error

swagger:response getInfrastructureAccountInternalServerError
*/
type GetInfrastructureAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetInfrastructureAccountInternalServerError creates GetInfrastructureAccountInternalServerError with default headers values
func NewGetInfrastructureAccountInternalServerError() *GetInfrastructureAccountInternalServerError {
	return &GetInfrastructureAccountInternalServerError{}
}

// WithPayload adds the payload to the get infrastructure account internal server error response
func (o *GetInfrastructureAccountInternalServerError) WithPayload(payload *models.Error) *GetInfrastructureAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get infrastructure account internal server error response
func (o *GetInfrastructureAccountInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInfrastructureAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
