package infrastructure_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type ListInfrastructureAccountsOK
const ListInfrastructureAccountsOKCode int = 200

/*ListInfrastructureAccountsOK List of all infrastructure accounts.

swagger:response listInfrastructureAccountsOK
*/
type ListInfrastructureAccountsOK struct {

	/*
	  In: Body
	*/
	Payload ListInfrastructureAccountsOKBody `json:"body,omitempty"`
}

// NewListInfrastructureAccountsOK creates ListInfrastructureAccountsOK with default headers values
func NewListInfrastructureAccountsOK() *ListInfrastructureAccountsOK {
	return &ListInfrastructureAccountsOK{}
}

// WithPayload adds the payload to the list infrastructure accounts o k response
func (o *ListInfrastructureAccountsOK) WithPayload(payload ListInfrastructureAccountsOKBody) *ListInfrastructureAccountsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list infrastructure accounts o k response
func (o *ListInfrastructureAccountsOK) SetPayload(payload ListInfrastructureAccountsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListInfrastructureAccountsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// HTTP code for type ListInfrastructureAccountsUnauthorized
const ListInfrastructureAccountsUnauthorizedCode int = 401

/*ListInfrastructureAccountsUnauthorized Unauthorized

swagger:response listInfrastructureAccountsUnauthorized
*/
type ListInfrastructureAccountsUnauthorized struct {
}

// NewListInfrastructureAccountsUnauthorized creates ListInfrastructureAccountsUnauthorized with default headers values
func NewListInfrastructureAccountsUnauthorized() *ListInfrastructureAccountsUnauthorized {
	return &ListInfrastructureAccountsUnauthorized{}
}

// WriteResponse to the client
func (o *ListInfrastructureAccountsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type ListInfrastructureAccountsForbidden
const ListInfrastructureAccountsForbiddenCode int = 403

/*ListInfrastructureAccountsForbidden Forbidden

swagger:response listInfrastructureAccountsForbidden
*/
type ListInfrastructureAccountsForbidden struct {
}

// NewListInfrastructureAccountsForbidden creates ListInfrastructureAccountsForbidden with default headers values
func NewListInfrastructureAccountsForbidden() *ListInfrastructureAccountsForbidden {
	return &ListInfrastructureAccountsForbidden{}
}

// WriteResponse to the client
func (o *ListInfrastructureAccountsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// HTTP code for type ListInfrastructureAccountsInternalServerError
const ListInfrastructureAccountsInternalServerErrorCode int = 500

/*ListInfrastructureAccountsInternalServerError Unexpected error

swagger:response listInfrastructureAccountsInternalServerError
*/
type ListInfrastructureAccountsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListInfrastructureAccountsInternalServerError creates ListInfrastructureAccountsInternalServerError with default headers values
func NewListInfrastructureAccountsInternalServerError() *ListInfrastructureAccountsInternalServerError {
	return &ListInfrastructureAccountsInternalServerError{}
}

// WithPayload adds the payload to the list infrastructure accounts internal server error response
func (o *ListInfrastructureAccountsInternalServerError) WithPayload(payload *models.Error) *ListInfrastructureAccountsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list infrastructure accounts internal server error response
func (o *ListInfrastructureAccountsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListInfrastructureAccountsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
