package infrastructure_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type UpdateInfrastructureAccountOK
const UpdateInfrastructureAccountOKCode int = 200

/*UpdateInfrastructureAccountOK The infrastructure account update request is accepted

swagger:response updateInfrastructureAccountOK
*/
type UpdateInfrastructureAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.InfrastructureAccount `json:"body,omitempty"`
}

// NewUpdateInfrastructureAccountOK creates UpdateInfrastructureAccountOK with default headers values
func NewUpdateInfrastructureAccountOK() *UpdateInfrastructureAccountOK {
	return &UpdateInfrastructureAccountOK{}
}

// WithPayload adds the payload to the update infrastructure account o k response
func (o *UpdateInfrastructureAccountOK) WithPayload(payload *models.InfrastructureAccount) *UpdateInfrastructureAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update infrastructure account o k response
func (o *UpdateInfrastructureAccountOK) SetPayload(payload *models.InfrastructureAccount) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateInfrastructureAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type UpdateInfrastructureAccountUnauthorized
const UpdateInfrastructureAccountUnauthorizedCode int = 401

/*UpdateInfrastructureAccountUnauthorized Unauthorized

swagger:response updateInfrastructureAccountUnauthorized
*/
type UpdateInfrastructureAccountUnauthorized struct {
}

// NewUpdateInfrastructureAccountUnauthorized creates UpdateInfrastructureAccountUnauthorized with default headers values
func NewUpdateInfrastructureAccountUnauthorized() *UpdateInfrastructureAccountUnauthorized {
	return &UpdateInfrastructureAccountUnauthorized{}
}

// WriteResponse to the client
func (o *UpdateInfrastructureAccountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type UpdateInfrastructureAccountForbidden
const UpdateInfrastructureAccountForbiddenCode int = 403

/*UpdateInfrastructureAccountForbidden Forbidden

swagger:response updateInfrastructureAccountForbidden
*/
type UpdateInfrastructureAccountForbidden struct {
}

// NewUpdateInfrastructureAccountForbidden creates UpdateInfrastructureAccountForbidden with default headers values
func NewUpdateInfrastructureAccountForbidden() *UpdateInfrastructureAccountForbidden {
	return &UpdateInfrastructureAccountForbidden{}
}

// WriteResponse to the client
func (o *UpdateInfrastructureAccountForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// HTTP code for type UpdateInfrastructureAccountNotFound
const UpdateInfrastructureAccountNotFoundCode int = 404

/*UpdateInfrastructureAccountNotFound InfrastructureAccount not found

swagger:response updateInfrastructureAccountNotFound
*/
type UpdateInfrastructureAccountNotFound struct {
}

// NewUpdateInfrastructureAccountNotFound creates UpdateInfrastructureAccountNotFound with default headers values
func NewUpdateInfrastructureAccountNotFound() *UpdateInfrastructureAccountNotFound {
	return &UpdateInfrastructureAccountNotFound{}
}

// WriteResponse to the client
func (o *UpdateInfrastructureAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// HTTP code for type UpdateInfrastructureAccountInternalServerError
const UpdateInfrastructureAccountInternalServerErrorCode int = 500

/*UpdateInfrastructureAccountInternalServerError Unexpected error

swagger:response updateInfrastructureAccountInternalServerError
*/
type UpdateInfrastructureAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateInfrastructureAccountInternalServerError creates UpdateInfrastructureAccountInternalServerError with default headers values
func NewUpdateInfrastructureAccountInternalServerError() *UpdateInfrastructureAccountInternalServerError {
	return &UpdateInfrastructureAccountInternalServerError{}
}

// WithPayload adds the payload to the update infrastructure account internal server error response
func (o *UpdateInfrastructureAccountInternalServerError) WithPayload(payload *models.Error) *UpdateInfrastructureAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update infrastructure account internal server error response
func (o *UpdateInfrastructureAccountInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateInfrastructureAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
