package node_pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type DeleteNodePoolNoContent
const DeleteNodePoolNoContentCode int = 204

/*DeleteNodePoolNoContent Node pool deleted.

swagger:response deleteNodePoolNoContent
*/
type DeleteNodePoolNoContent struct {
}

// NewDeleteNodePoolNoContent creates DeleteNodePoolNoContent with default headers values
func NewDeleteNodePoolNoContent() *DeleteNodePoolNoContent {
	return &DeleteNodePoolNoContent{}
}

// WriteResponse to the client
func (o *DeleteNodePoolNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// HTTP code for type DeleteNodePoolBadRequest
const DeleteNodePoolBadRequestCode int = 400

/*DeleteNodePoolBadRequest Invalid request

swagger:response deleteNodePoolBadRequest
*/
type DeleteNodePoolBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteNodePoolBadRequest creates DeleteNodePoolBadRequest with default headers values
func NewDeleteNodePoolBadRequest() *DeleteNodePoolBadRequest {
	return &DeleteNodePoolBadRequest{}
}

// WithPayload adds the payload to the delete node pool bad request response
func (o *DeleteNodePoolBadRequest) WithPayload(payload *models.Error) *DeleteNodePoolBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete node pool bad request response
func (o *DeleteNodePoolBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteNodePoolBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type DeleteNodePoolUnauthorized
const DeleteNodePoolUnauthorizedCode int = 401

/*DeleteNodePoolUnauthorized Unauthorized

swagger:response deleteNodePoolUnauthorized
*/
type DeleteNodePoolUnauthorized struct {
}

// NewDeleteNodePoolUnauthorized creates DeleteNodePoolUnauthorized with default headers values
func NewDeleteNodePoolUnauthorized() *DeleteNodePoolUnauthorized {
	return &DeleteNodePoolUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteNodePoolUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type DeleteNodePoolForbidden
const DeleteNodePoolForbiddenCode int = 403

/*DeleteNodePoolForbidden Forbidden

swagger:response deleteNodePoolForbidden
*/
type DeleteNodePoolForbidden struct {
}

// NewDeleteNodePoolForbidden creates DeleteNodePoolForbidden with default headers values
func NewDeleteNodePoolForbidden() *DeleteNodePoolForbidden {
	return &DeleteNodePoolForbidden{}
}

// WriteResponse to the client
func (o *DeleteNodePoolForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// HTTP code for type DeleteNodePoolNotFound
const DeleteNodePoolNotFoundCode int = 404

/*DeleteNodePoolNotFound Node pool not found

swagger:response deleteNodePoolNotFound
*/
type DeleteNodePoolNotFound struct {
}

// NewDeleteNodePoolNotFound creates DeleteNodePoolNotFound with default headers values
func NewDeleteNodePoolNotFound() *DeleteNodePoolNotFound {
	return &DeleteNodePoolNotFound{}
}

// WriteResponse to the client
func (o *DeleteNodePoolNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// HTTP code for type DeleteNodePoolInternalServerError
const DeleteNodePoolInternalServerErrorCode int = 500

/*DeleteNodePoolInternalServerError Unexpected error

swagger:response deleteNodePoolInternalServerError
*/
type DeleteNodePoolInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteNodePoolInternalServerError creates DeleteNodePoolInternalServerError with default headers values
func NewDeleteNodePoolInternalServerError() *DeleteNodePoolInternalServerError {
	return &DeleteNodePoolInternalServerError{}
}

// WithPayload adds the payload to the delete node pool internal server error response
func (o *DeleteNodePoolInternalServerError) WithPayload(payload *models.Error) *DeleteNodePoolInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete node pool internal server error response
func (o *DeleteNodePoolInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteNodePoolInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
