package node_pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type ListNodePoolsOK
const ListNodePoolsOKCode int = 200

/*ListNodePoolsOK List of node pools

swagger:response listNodePoolsOK
*/
type ListNodePoolsOK struct {

	/*
	  In: Body
	*/
	Payload ListNodePoolsOKBody `json:"body,omitempty"`
}

// NewListNodePoolsOK creates ListNodePoolsOK with default headers values
func NewListNodePoolsOK() *ListNodePoolsOK {
	return &ListNodePoolsOK{}
}

// WithPayload adds the payload to the list node pools o k response
func (o *ListNodePoolsOK) WithPayload(payload ListNodePoolsOKBody) *ListNodePoolsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list node pools o k response
func (o *ListNodePoolsOK) SetPayload(payload ListNodePoolsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListNodePoolsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// HTTP code for type ListNodePoolsUnauthorized
const ListNodePoolsUnauthorizedCode int = 401

/*ListNodePoolsUnauthorized Unauthorized

swagger:response listNodePoolsUnauthorized
*/
type ListNodePoolsUnauthorized struct {
}

// NewListNodePoolsUnauthorized creates ListNodePoolsUnauthorized with default headers values
func NewListNodePoolsUnauthorized() *ListNodePoolsUnauthorized {
	return &ListNodePoolsUnauthorized{}
}

// WriteResponse to the client
func (o *ListNodePoolsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type ListNodePoolsForbidden
const ListNodePoolsForbiddenCode int = 403

/*ListNodePoolsForbidden Forbidden

swagger:response listNodePoolsForbidden
*/
type ListNodePoolsForbidden struct {
}

// NewListNodePoolsForbidden creates ListNodePoolsForbidden with default headers values
func NewListNodePoolsForbidden() *ListNodePoolsForbidden {
	return &ListNodePoolsForbidden{}
}

// WriteResponse to the client
func (o *ListNodePoolsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// HTTP code for type ListNodePoolsInternalServerError
const ListNodePoolsInternalServerErrorCode int = 500

/*ListNodePoolsInternalServerError Unexpected error

swagger:response listNodePoolsInternalServerError
*/
type ListNodePoolsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListNodePoolsInternalServerError creates ListNodePoolsInternalServerError with default headers values
func NewListNodePoolsInternalServerError() *ListNodePoolsInternalServerError {
	return &ListNodePoolsInternalServerError{}
}

// WithPayload adds the payload to the list node pools internal server error response
func (o *ListNodePoolsInternalServerError) WithPayload(payload *models.Error) *ListNodePoolsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list node pools internal server error response
func (o *ListNodePoolsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListNodePoolsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
