package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type DeleteClusterNoContent
const DeleteClusterNoContentCode int = 204

/*DeleteClusterNoContent Cluster deleted

swagger:response deleteClusterNoContent
*/
type DeleteClusterNoContent struct {
}

// NewDeleteClusterNoContent creates DeleteClusterNoContent with default headers values
func NewDeleteClusterNoContent() *DeleteClusterNoContent {
	return &DeleteClusterNoContent{}
}

// WriteResponse to the client
func (o *DeleteClusterNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// HTTP code for type DeleteClusterBadRequest
const DeleteClusterBadRequestCode int = 400

/*DeleteClusterBadRequest Invalid request

swagger:response deleteClusterBadRequest
*/
type DeleteClusterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteClusterBadRequest creates DeleteClusterBadRequest with default headers values
func NewDeleteClusterBadRequest() *DeleteClusterBadRequest {
	return &DeleteClusterBadRequest{}
}

// WithPayload adds the payload to the delete cluster bad request response
func (o *DeleteClusterBadRequest) WithPayload(payload *models.Error) *DeleteClusterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster bad request response
func (o *DeleteClusterBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type DeleteClusterUnauthorized
const DeleteClusterUnauthorizedCode int = 401

/*DeleteClusterUnauthorized Unauthorized

swagger:response deleteClusterUnauthorized
*/
type DeleteClusterUnauthorized struct {
}

// NewDeleteClusterUnauthorized creates DeleteClusterUnauthorized with default headers values
func NewDeleteClusterUnauthorized() *DeleteClusterUnauthorized {
	return &DeleteClusterUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteClusterUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type DeleteClusterForbidden
const DeleteClusterForbiddenCode int = 403

/*DeleteClusterForbidden Forbidden

swagger:response deleteClusterForbidden
*/
type DeleteClusterForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteClusterForbidden creates DeleteClusterForbidden with default headers values
func NewDeleteClusterForbidden() *DeleteClusterForbidden {
	return &DeleteClusterForbidden{}
}

// WithPayload adds the payload to the delete cluster forbidden response
func (o *DeleteClusterForbidden) WithPayload(payload *models.Error) *DeleteClusterForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster forbidden response
func (o *DeleteClusterForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type DeleteClusterNotFound
const DeleteClusterNotFoundCode int = 404

/*DeleteClusterNotFound Cluster not found

swagger:response deleteClusterNotFound
*/
type DeleteClusterNotFound struct {
}

// NewDeleteClusterNotFound creates DeleteClusterNotFound with default headers values
func NewDeleteClusterNotFound() *DeleteClusterNotFound {
	return &DeleteClusterNotFound{}
}

// WriteResponse to the client
func (o *DeleteClusterNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// HTTP code for type DeleteClusterInternalServerError
const DeleteClusterInternalServerErrorCode int = 500

/*DeleteClusterInternalServerError Unexpected error

swagger:response deleteClusterInternalServerError
*/
type DeleteClusterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteClusterInternalServerError creates DeleteClusterInternalServerError with default headers values
func NewDeleteClusterInternalServerError() *DeleteClusterInternalServerError {
	return &DeleteClusterInternalServerError{}
}

// WithPayload adds the payload to the delete cluster internal server error response
func (o *DeleteClusterInternalServerError) WithPayload(payload *models.Error) *DeleteClusterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster internal server error response
func (o *DeleteClusterInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
