package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type ListClustersOK
const ListClustersOKCode int = 200

/*ListClustersOK List of all Kubernetes clusters.

swagger:response listClustersOK
*/
type ListClustersOK struct {

	/*
	  In: Body
	*/
	Payload ListClustersOKBody `json:"body,omitempty"`
}

// NewListClustersOK creates ListClustersOK with default headers values
func NewListClustersOK() *ListClustersOK {
	return &ListClustersOK{}
}

// WithPayload adds the payload to the list clusters o k response
func (o *ListClustersOK) WithPayload(payload ListClustersOKBody) *ListClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list clusters o k response
func (o *ListClustersOK) SetPayload(payload ListClustersOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// HTTP code for type ListClustersUnauthorized
const ListClustersUnauthorizedCode int = 401

/*ListClustersUnauthorized Unauthorized

swagger:response listClustersUnauthorized
*/
type ListClustersUnauthorized struct {
}

// NewListClustersUnauthorized creates ListClustersUnauthorized with default headers values
func NewListClustersUnauthorized() *ListClustersUnauthorized {
	return &ListClustersUnauthorized{}
}

// WriteResponse to the client
func (o *ListClustersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type ListClustersForbidden
const ListClustersForbiddenCode int = 403

/*ListClustersForbidden Forbidden

swagger:response listClustersForbidden
*/
type ListClustersForbidden struct {
}

// NewListClustersForbidden creates ListClustersForbidden with default headers values
func NewListClustersForbidden() *ListClustersForbidden {
	return &ListClustersForbidden{}
}

// WriteResponse to the client
func (o *ListClustersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// HTTP code for type ListClustersInternalServerError
const ListClustersInternalServerErrorCode int = 500

/*ListClustersInternalServerError Unexpected error

swagger:response listClustersInternalServerError
*/
type ListClustersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListClustersInternalServerError creates ListClustersInternalServerError with default headers values
func NewListClustersInternalServerError() *ListClustersInternalServerError {
	return &ListClustersInternalServerError{}
}

// WithPayload adds the payload to the list clusters internal server error response
func (o *ListClustersInternalServerError) WithPayload(payload *models.Error) *ListClustersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list clusters internal server error response
func (o *ListClustersInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListClustersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
