package config_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type AddOrUpdateConfigItemOK
const AddOrUpdateConfigItemOKCode int = 200

/*AddOrUpdateConfigItemOK The config items add/update request is accepted.

swagger:response addOrUpdateConfigItemOK
*/
type AddOrUpdateConfigItemOK struct {

	/*
	  In: Body
	*/
	Payload *models.ConfigValue `json:"body,omitempty"`
}

// NewAddOrUpdateConfigItemOK creates AddOrUpdateConfigItemOK with default headers values
func NewAddOrUpdateConfigItemOK() *AddOrUpdateConfigItemOK {
	return &AddOrUpdateConfigItemOK{}
}

// WithPayload adds the payload to the add or update config item o k response
func (o *AddOrUpdateConfigItemOK) WithPayload(payload *models.ConfigValue) *AddOrUpdateConfigItemOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add or update config item o k response
func (o *AddOrUpdateConfigItemOK) SetPayload(payload *models.ConfigValue) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddOrUpdateConfigItemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type AddOrUpdateConfigItemBadRequest
const AddOrUpdateConfigItemBadRequestCode int = 400

/*AddOrUpdateConfigItemBadRequest Invalid request

swagger:response addOrUpdateConfigItemBadRequest
*/
type AddOrUpdateConfigItemBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddOrUpdateConfigItemBadRequest creates AddOrUpdateConfigItemBadRequest with default headers values
func NewAddOrUpdateConfigItemBadRequest() *AddOrUpdateConfigItemBadRequest {
	return &AddOrUpdateConfigItemBadRequest{}
}

// WithPayload adds the payload to the add or update config item bad request response
func (o *AddOrUpdateConfigItemBadRequest) WithPayload(payload *models.Error) *AddOrUpdateConfigItemBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add or update config item bad request response
func (o *AddOrUpdateConfigItemBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddOrUpdateConfigItemBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type AddOrUpdateConfigItemUnauthorized
const AddOrUpdateConfigItemUnauthorizedCode int = 401

/*AddOrUpdateConfigItemUnauthorized Unauthorized

swagger:response addOrUpdateConfigItemUnauthorized
*/
type AddOrUpdateConfigItemUnauthorized struct {
}

// NewAddOrUpdateConfigItemUnauthorized creates AddOrUpdateConfigItemUnauthorized with default headers values
func NewAddOrUpdateConfigItemUnauthorized() *AddOrUpdateConfigItemUnauthorized {
	return &AddOrUpdateConfigItemUnauthorized{}
}

// WriteResponse to the client
func (o *AddOrUpdateConfigItemUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type AddOrUpdateConfigItemForbidden
const AddOrUpdateConfigItemForbiddenCode int = 403

/*AddOrUpdateConfigItemForbidden Forbidden

swagger:response addOrUpdateConfigItemForbidden
*/
type AddOrUpdateConfigItemForbidden struct {
}

// NewAddOrUpdateConfigItemForbidden creates AddOrUpdateConfigItemForbidden with default headers values
func NewAddOrUpdateConfigItemForbidden() *AddOrUpdateConfigItemForbidden {
	return &AddOrUpdateConfigItemForbidden{}
}

// WriteResponse to the client
func (o *AddOrUpdateConfigItemForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// HTTP code for type AddOrUpdateConfigItemInternalServerError
const AddOrUpdateConfigItemInternalServerErrorCode int = 500

/*AddOrUpdateConfigItemInternalServerError Unexpected error

swagger:response addOrUpdateConfigItemInternalServerError
*/
type AddOrUpdateConfigItemInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddOrUpdateConfigItemInternalServerError creates AddOrUpdateConfigItemInternalServerError with default headers values
func NewAddOrUpdateConfigItemInternalServerError() *AddOrUpdateConfigItemInternalServerError {
	return &AddOrUpdateConfigItemInternalServerError{}
}

// WithPayload adds the payload to the add or update config item internal server error response
func (o *AddOrUpdateConfigItemInternalServerError) WithPayload(payload *models.Error) *AddOrUpdateConfigItemInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add or update config item internal server error response
func (o *AddOrUpdateConfigItemInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddOrUpdateConfigItemInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
