package config_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type DeleteConfigItemNoContent
const DeleteConfigItemNoContentCode int = 204

/*DeleteConfigItemNoContent Config item deleted.

swagger:response deleteConfigItemNoContent
*/
type DeleteConfigItemNoContent struct {
}

// NewDeleteConfigItemNoContent creates DeleteConfigItemNoContent with default headers values
func NewDeleteConfigItemNoContent() *DeleteConfigItemNoContent {
	return &DeleteConfigItemNoContent{}
}

// WriteResponse to the client
func (o *DeleteConfigItemNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// HTTP code for type DeleteConfigItemBadRequest
const DeleteConfigItemBadRequestCode int = 400

/*DeleteConfigItemBadRequest Invalid request

swagger:response deleteConfigItemBadRequest
*/
type DeleteConfigItemBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigItemBadRequest creates DeleteConfigItemBadRequest with default headers values
func NewDeleteConfigItemBadRequest() *DeleteConfigItemBadRequest {
	return &DeleteConfigItemBadRequest{}
}

// WithPayload adds the payload to the delete config item bad request response
func (o *DeleteConfigItemBadRequest) WithPayload(payload *models.Error) *DeleteConfigItemBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config item bad request response
func (o *DeleteConfigItemBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigItemBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type DeleteConfigItemUnauthorized
const DeleteConfigItemUnauthorizedCode int = 401

/*DeleteConfigItemUnauthorized Unauthorized

swagger:response deleteConfigItemUnauthorized
*/
type DeleteConfigItemUnauthorized struct {
}

// NewDeleteConfigItemUnauthorized creates DeleteConfigItemUnauthorized with default headers values
func NewDeleteConfigItemUnauthorized() *DeleteConfigItemUnauthorized {
	return &DeleteConfigItemUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteConfigItemUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// HTTP code for type DeleteConfigItemForbidden
const DeleteConfigItemForbiddenCode int = 403

/*DeleteConfigItemForbidden Forbidden

swagger:response deleteConfigItemForbidden
*/
type DeleteConfigItemForbidden struct {
}

// NewDeleteConfigItemForbidden creates DeleteConfigItemForbidden with default headers values
func NewDeleteConfigItemForbidden() *DeleteConfigItemForbidden {
	return &DeleteConfigItemForbidden{}
}

// WriteResponse to the client
func (o *DeleteConfigItemForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// HTTP code for type DeleteConfigItemNotFound
const DeleteConfigItemNotFoundCode int = 404

/*DeleteConfigItemNotFound Config item not found

swagger:response deleteConfigItemNotFound
*/
type DeleteConfigItemNotFound struct {
}

// NewDeleteConfigItemNotFound creates DeleteConfigItemNotFound with default headers values
func NewDeleteConfigItemNotFound() *DeleteConfigItemNotFound {
	return &DeleteConfigItemNotFound{}
}

// WriteResponse to the client
func (o *DeleteConfigItemNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// HTTP code for type DeleteConfigItemInternalServerError
const DeleteConfigItemInternalServerErrorCode int = 500

/*DeleteConfigItemInternalServerError Unexpected error

swagger:response deleteConfigItemInternalServerError
*/
type DeleteConfigItemInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigItemInternalServerError creates DeleteConfigItemInternalServerError with default headers values
func NewDeleteConfigItemInternalServerError() *DeleteConfigItemInternalServerError {
	return &DeleteConfigItemInternalServerError{}
}

// WithPayload adds the payload to the delete config item internal server error response
func (o *DeleteConfigItemInternalServerError) WithPayload(payload *models.Error) *DeleteConfigItemInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config item internal server error response
func (o *DeleteConfigItemInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigItemInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
