package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/gin-gonic/gin"
	"github.com/go-openapi/errors"
	"github.com/mikkeloscar/gin-swagger/api"
)

// BusinessLogicGetHealth executes the core logic of the related
// route endpoint.
func BusinessLogicGetHealth(f func(ctx *gin.Context) *api.Response) gin.HandlerFunc {
	return func(ctx *gin.Context) {

		resp := f(ctx)
		ctx.JSON(resp.Code, resp.Body)
	}
}

// GetHealthParams contains all the bound params for the get health operation
// typically these are obtained from a http.Request
//
// swagger:parameters getHealth
type GetHealthParams struct {
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetHealthParams) bindRequest(ctx *gin.Context) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
