package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mikkeloscar/gin-swagger/example/models"
)

// HTTP code for type GetHealthOK
const GetHealthOKCode int = 200

/*GetHealthOK Application is healthy

swagger:response getHealthOK
*/
type GetHealthOK struct {

	/*
	  In: Body
	*/
	Payload *models.Health `json:"body,omitempty"`
}

// NewGetHealthOK creates GetHealthOK with default headers values
func NewGetHealthOK() *GetHealthOK {
	return &GetHealthOK{}
}

// WithPayload adds the payload to the get health o k response
func (o *GetHealthOK) WithPayload(payload *models.Health) *GetHealthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get health o k response
func (o *GetHealthOK) SetPayload(payload *models.Health) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type GetHealthServiceUnavailable
const GetHealthServiceUnavailableCode int = 503

/*GetHealthServiceUnavailable Application is unhealthy

swagger:response getHealthServiceUnavailable
*/
type GetHealthServiceUnavailable struct {
}

// NewGetHealthServiceUnavailable creates GetHealthServiceUnavailable with default headers values
func NewGetHealthServiceUnavailable() *GetHealthServiceUnavailable {
	return &GetHealthServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetHealthServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
