// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClusterStatus cluster status
// swagger:model ClusterStatus

type ClusterStatus struct {

	// Current version of the cluster. This can refer to a commit hash or
	// any valid version string in the context.
	//
	CurrentVersion string `json:"current_version,omitempty"`

	// Last working version of the cluster. This can refer to a commit
	// hash or any valid version string in the context. In case any
	// problems are defined for the current_version then it should be
	// safe to roll back to this last version.
	//
	LastVersion string `json:"last_version,omitempty"`

	// Next version of the cluster. This field indicates that the cluster is
	// being updated to a new version. This can refer to a commit hash or any
	// valid version string in the context.
	//
	NextVersion string `json:"next_version,omitempty"`

	// problems
	Problems ClusterStatusProblems `json:"problems"`
}

/* polymorph ClusterStatus current_version false */

/* polymorph ClusterStatus last_version false */

/* polymorph ClusterStatus next_version false */

/* polymorph ClusterStatus problems false */

// Validate validates this cluster status
func (m *ClusterStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterStatus) UnmarshalBinary(b []byte) error {
	var res ClusterStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
